"""add t_credit_notes table

Revision ID: 1545d0e3e26c
Revises: 
Create Date: 2025-12-02 14:12:00.286229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1545d0e3e26c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_return_id', sa.Integer(), nullable=False),
    sa.Column('original_invoice_id', sa.Integer(), nullable=False),
    sa.Column('applied_sale_id', sa.Integer(), nullable=True),
    sa.Column('formatted_number', sa.String(length=100), nullable=False),
    sa.Column('timbrado', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['applied_sale_id'], ['t_sales.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['t_invoices.id'], ),
    sa.ForeignKeyConstraint(['sales_return_id'], ['t_sales_returns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formatted_number'),
    sa.UniqueConstraint('sales_return_id')
    )
    op.drop_table('t_modulos_sistema')
    op.drop_table('t_product_damages')
    op.drop_table('t_cash_register_payments')
    with op.batch_alter_table('t_cash', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::text"))

    with op.batch_alter_table('t_cash_register_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cash_register_id'))
        batch_op.drop_index(batch_op.f('idx_payment_method_id'))
        batch_op.create_foreign_key(None, 't_cash_register', ['cash_register_id'], ['id'])

    with op.batch_alter_table('t_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_categories_name_key'), type_='unique')

    with op.batch_alter_table('t_invoice_formats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_invoice_formats_name_key'), type_='unique')

    with op.batch_alter_table('t_invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['formatted_number'])
        batch_op.create_unique_constraint(None, ['sale_id'])
        batch_op.drop_constraint(batch_op.f('t_invoices_sale_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_sales', ['sale_id'], ['id'])

    with op.batch_alter_table('t_permisos', schema=None) as batch_op:
        batch_op.drop_column('init_route_path')

    with op.batch_alter_table('t_products', schema=None) as batch_op:
        batch_op.alter_column('tax_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('t_products_barcode_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_t_products_cod_interno'), type_='unique')

    with op.batch_alter_table('t_purchase_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_purchase_details_purchase_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_purchases', ['purchase_id'], ['id'])

    with op.batch_alter_table('t_purchase_status', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('t_purchase_status_status_name_key'), type_='unique')

    with op.batch_alter_table('t_purchases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_purchases_supplier_id_invoice_number_key'), type_='unique')

    with op.batch_alter_table('t_return_reasons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_return_reasons_code_key'), type_='unique')

    with op.batch_alter_table('t_sales_details', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('t_sales_details_sale_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_sales', ['sale_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('t_sales_return_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_sales_return_details_return_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 't_sales_returns', ['return_id'], ['id'])

    with op.batch_alter_table('t_sales_returns', schema=None) as batch_op:
        batch_op.alter_column('return_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'CONFIRMED'::character varying"))

    with op.batch_alter_table('t_suppliers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ruc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_t_suppliers_ruc'), type_='unique')
        batch_op.drop_index(batch_op.f('ux_t_suppliers_name_lower'))

    with op.batch_alter_table('t_taxes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_taxes_name_key'), type_='unique')

    with op.batch_alter_table('t_usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('t_taxes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('t_taxes_name_key'), ['name'])

    with op.batch_alter_table('t_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_t_suppliers_name_lower'), [sa.literal_column('lower(name::text)')], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_t_suppliers_ruc'), ['ruc'])
        batch_op.alter_column('phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('ruc',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('t_sales_returns', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CONFIRMED'::character varying"))
        batch_op.alter_column('return_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('t_sales_return_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_sales_return_details_return_id_fkey'), 't_sales_returns', ['return_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('t_sales_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_sales_details_sale_id_fkey'), 't_sales', ['sale_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('t_return_reasons', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('t_return_reasons_code_key'), ['code'])

    with op.batch_alter_table('t_purchases', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('t_purchases_supplier_id_invoice_number_key'), ['supplier_id', 'invoice_number'])

    with op.batch_alter_table('t_purchase_status', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('t_purchase_status_status_name_key'), ['status_name'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('t_purchase_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_purchase_details_purchase_id_fkey'), 't_purchases', ['purchase_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('t_products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_t_products_cod_interno'), ['cod_interno'])
        batch_op.create_unique_constraint(batch_op.f('t_products_barcode_key'), ['barcode'])
        batch_op.alter_column('tax_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('t_permisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('init_route_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('t_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('t_invoices_sale_id_fkey'), 't_sales', ['sale_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('t_invoice_formats', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('t_invoice_formats_name_key'), ['name'])

    with op.batch_alter_table('t_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('t_categories_name_key'), ['name'])

    with op.batch_alter_table('t_cash_register_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cash_register_id'), ['cash_register_id'], unique=False)

    with op.batch_alter_table('t_cash', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::text"))

    op.create_table('t_cash_register_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cash_register_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['t_payment_methods.id'], name=op.f('t_cash_register_payments_payment_method_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('t_cash_register_payments_pkey'))
    )
    op.create_table('t_product_damages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_detail_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_detail_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('reason_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['t_products.id'], name=op.f('t_product_damages_product_id_fkey')),
    sa.ForeignKeyConstraint(['reason_id'], ['t_return_reasons.id'], name=op.f('t_product_damages_reason_id_fkey')),
    sa.ForeignKeyConstraint(['return_detail_id'], ['t_sales_return_details.id'], name=op.f('t_product_damages_return_detail_id_fkey')),
    sa.ForeignKeyConstraint(['sale_detail_id'], ['t_sales_details.id'], name=op.f('t_product_damages_sale_detail_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('t_product_damages_pkey'))
    )
    op.create_table('t_modulos_sistema',
    sa.Column('id_modulo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_modulo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_modulo', name=op.f('t_modulos_sistema_pkey')),
    sa.UniqueConstraint('nombre_modulo', name=op.f('t_modulos_sistema_nombre_modulo_key'))
    )
    op.drop_table('t_credit_notes')
    # ### end Alembic commands ###
