"""Add historial_accesos table

Revision ID: 165d8fdbfa06
Revises: 1545d0e3e26c
Create Date: 2026-03-14 16:16:30.876028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165d8fdbfa06'
down_revision = '1545d0e3e26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_table('t_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('historial_accesos',
    sa.Column('id_acceso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('username_intentado', sa.String(length=50), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('evento', sa.String(length=20), nullable=True),
    sa.Column('ip_cliente', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('motivo_fallo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_acceso')
    )
    with op.batch_alter_table('historial_accesos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_accesos_fecha_hora'), ['fecha_hora'], unique=False)

    op.drop_table('conceptos_contables')
    with op.batch_alter_table('asientos_contables', schema=None) as batch_op:
        batch_op.alter_column('glosa',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clientes_documento_key'), type_='unique')

    with op.batch_alter_table('creditos', schema=None) as batch_op:
        batch_op.drop_column('fecha_primer_pago')

    with op.batch_alter_table('detalles_credito', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_credito_det'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'creditos', ['id_credito'], ['id_credito'])

    with op.batch_alter_table('movimientos_contables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_asiento'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'asientos_contables', ['id_asiento'], ['id_asiento'])

    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('movimientos_contables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_asiento'), 'asientos_contables', ['id_asiento'], ['id_asiento'], ondelete='CASCADE')

    with op.batch_alter_table('detalles_credito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_credito_det'), 'creditos', ['id_credito'], ['id_credito'], ondelete='CASCADE')

    with op.batch_alter_table('creditos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_primer_pago', sa.DATE(), autoincrement=False, nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('clientes_documento_key'), ['documento'])

    with op.batch_alter_table('asientos_contables', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('glosa',
               existing_type=sa.TEXT(),
               nullable=False)

    op.create_table('conceptos_contables',
    sa.Column('id_concepto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.CheckConstraint("tipo::text = ANY (ARRAY['INGRESO'::character varying::text, 'EGRESO'::character varying::text])", name=op.f('conceptos_contables_tipo_check')),
    sa.PrimaryKeyConstraint('id_concepto', name=op.f('conceptos_contables_pkey'))
    )
    with op.batch_alter_table('historial_accesos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_accesos_fecha_hora'))

    op.drop_table('historial_accesos')
    op.drop_table('t_status')
    op.drop_table('t_company_settings')
    # ### end Alembic commands ###
